spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345
    url: jdbc:mysql://127.0.0.1:3306/db_shiro?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false



#logging:
#  level:
#    com.hcy.shirodemo.mapper.UserMapper : DEBUG
